name: Lint & Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          scope: '@changesets-bitbucket'

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
